### ISSUE TITLE
Error when downloading translations

### ISSUE THREAD

**Issue by Ryuinferno** [crowdin/crowdin-cli-v1#44]
I was using the latest version of crowdin-cli (at commit a8d20c1448973c4417649437e769eacb6a1e80ad) and I encountered this error message:

```
Extracting: `/packages/apps/Settings/res/values-ro-rRO/arrays.xml'
error: can't convert Zip::Entry into String
Failed to run cmd: crowdin-cli --config=crowdin/crowdin.yaml download -b branch
```

The error message was resolved once I reverted f687e31ab00db6a02df60b84839f6461056b3f39. I believe that this should be a simple fix, however since I have 0 experience with Ruby, so this is the most I can help with. Thank you.

**Comment by mamantoha** [comment]
Thanks for the report. Can you provide your configuration file?

Also, it will be helpful if you run as `GLI_DEBUG=true crowdin-cli download [...]` and put output here

**Comment by Ryuinferno** [comment]
OK, so here is the output log:

```
$ GLI_DEBUG=true crowdin-cli --config=crowdin/crowdin_mk.yaml download -b mkm
Building ZIP archive with the latest translations - OK
Extracting: `/external/mokee/MoKeeHelper/MoKeeHelper/res/values-ro-rRO/arrays.xml'
error: can't convert Zip::Entry into String
/var/lib/gems/1.9.1/gems/rubyzip-1.2.0/lib/zip/file.rb:361:in `initialize': can't convert Zip::Entry into String (TypeError)
from /var/lib/gems/1.9.1/gems/rubyzip-1.2.0/lib/zip/file.rb:361:in `exception'
from /var/lib/gems/1.9.1/gems/rubyzip-1.2.0/lib/zip/file.rb:361:in `raise'
from /var/lib/gems/1.9.1/gems/rubyzip-1.2.0/lib/zip/file.rb:361:in `get_entry'
from /var/lib/gems/1.9.1/gems/rubyzip-1.2.0/lib/zip/file.rb:302:in `extract'
from /var/lib/gems/1.9.1/gems/crowdin-cli-0.5.2/bin/crowdin-cli:272:in `block (2 levels) in unzip_file_with_translations'
from /var/lib/gems/1.9.1/gems/crowdin-cli-0.5.2/bin/crowdin-cli:258:in `each'
from /var/lib/gems/1.9.1/gems/crowdin-cli-0.5.2/bin/crowdin-cli:258:in `block in unzip_file_with_translations'
from /var/lib/gems/1.9.1/gems/rubyzip-1.2.0/lib/zip/file.rb:102:in `open'
from /var/lib/gems/1.9.1/gems/crowdin-cli-0.5.2/bin/crowdin-cli:257:in `unzip_file_with_translations'
from /var/lib/gems/1.9.1/gems/crowdin-cli-0.5.2/bin/crowdin-cli:870:in `block (2 levels) in <top (required)>'
from /var/lib/gems/1.9.1/gems/gli-2.13.4/lib/gli/command_support.rb:126:in `call'
from /var/lib/gems/1.9.1/gems/gli-2.13.4/lib/gli/command_support.rb:126:in `execute'
from /var/lib/gems/1.9.1/gems/gli-2.13.4/lib/gli/app_support.rb:296:in `block in call_command'
from /var/lib/gems/1.9.1/gems/gli-2.13.4/lib/gli/app_support.rb:309:in `call'
from /var/lib/gems/1.9.1/gems/gli-2.13.4/lib/gli/app_support.rb:309:in `call_command'
from /var/lib/gems/1.9.1/gems/gli-2.13.4/lib/gli/app_support.rb:83:in `run'
from /var/lib/gems/1.9.1/gems/crowdin-cli-0.5.2/bin/crowdin-cli:1264:in `<top (required)>'
from /usr/local/bin/crowdin-cli:23:in `load'
from /usr/local/bin/crowdin-cli:23:in `<main>'
```

The configuration file is here: https://github.com/MoKee/mk_crowdin/blob/mkm/crowdin/crowdin_mk.yaml

Hope these will help.

**Comment by mamantoha** [comment]
Well. I can't reproduce a bug, I can't fix it. So I just revert this commit. Please let me know it's working properly again.

Thank you.
